name: dachzeltfestival
description: Dachzeltfestival official app

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.0+26
environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  rxdart: ^0.24.1
  google_maps_flutter: ^1.2.0
  shared_preferences: 0.5.12+4
  firebase_core: ^0.5.2
  cloud_firestore: ^0.14.3
  flutter_sticky_header: ^0.5.0
  firebase_storage: ^5.0.1
  path_provider: ^1.6.24
  tuple: ^1.0.3
  permission_handler:
    git:
      url: git@github.com:jbxbergdev/flutter-permission-handler.git
      ref: dachzeltfestival_permissions
  url_launcher: ^5.7.10
  package_info: ^0.4.3+2
  firebase_auth: ^0.18.3
  flutter_markdown: ^0.5.0
  auto_size_text: ^2.1.0
  firebase_messaging: ^7.0.3
  google_fonts: ^1.1.1
  firebase_analytics: ^6.2.0
  bubble_tab_indicator: ^0.1.4
  sticky_headers: ^0.1.8+1
  sliding_up_panel: ^1.0.2
  cached_network_image: ^2.3.3
  assorted_layout_widgets: ^3.0.0
  webview_flutter: ^1.0.7
  injectable: ^1.0.5
  get_it: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.4
  injectable_generator: ^1.0.6

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  fonts:
    - family: CustomMarkers
      fonts:
        - asset: assets/fonts/CustomMarkers.ttf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/text/
