/// Flutter icons CustomMarkers
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomMarkers
///      fonts:
///       - asset: fonts/CustomMarkers.ttf
///
/// 
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class CustomMarkers {
  CustomMarkers._();

  static const _kFontFam = 'CustomMarkers';

  static const IconData bathtub = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData hashtag = const IconData(0xf292, fontFamily: _kFontFam);
}
